### ISSUE TITLE
resource replacement from gateways to the embedded node

### ISSUE THREAD

**Issue by rezad1393** [ipfs/ipfs-companion#1067] opened 2022-03-10 13:17 UTC
**Is your feature request related to a problem? Please describe.**
the ipfs.io is blocked in my country. so I thought I could use this addon to replace the https gateway with a node (embedded node for now) 
but websites that use ipfs for pictures just use a https gateway (like ipfs.io or cloudflare one)
so I wanted to fetch the pictures (not the main top-domain but pictures embedded in) via this addon embedded node.

**Describe the solution you'd like**
is there a way to intercept request to this websites and fetch the pictures via the node running either locally or embedded one in addon?

**Describe alternatives you've considered**
redirecting the resources with firefox addons (like https://addons.mozilla.org/en-US/firefox/addon/requestcontrol) doesnt work because the addon doesnt have a gateway for me to redirect to.

**Additional context**
firefox browser on linux.

**Comment by lidel** [comment] 2022-04-11 18:45
- ipfs-companion running on Firefox should be able to redirect images to your local ipfs-desktop or go-ipfs node as long their URL path starts with a valid `/ipfs/{cid}` 
  - this does not work if you use "embedded js-ipfs node" experiment

As this is not a bug report, closing, in the future ask support questions like this at https://discuss.ipfs.io/c/help/13 :pray:

**Closed by lidel** 2022-04-11 18:45 UTC
Labels: need/triage
