### ISSUE TITLE
Firefox won't redirect to local gateway

### ISSUE THREAD

**Issue by Geremia** [ipfs/ipfs-companion#1318] opened 2024-03-17 00:32 UTC
**Describe the bug**
Doesn't redirect to local gateway, despite have automatic enabled.

**To Reproduce**
1. Go to https://ipfs.io/ipfs/bafykbzacec75ad3qwvx4wy7omlw3oc6qbcy3dwjgu776zvs7iojhbx4n2wyze?filename=Penetration%20Testing%3A%20Penetration%20Testing%3A%20A%20Hands-On%20Guide%20--%20Connor%20Wallace%20--%202020%20--%208b3cb1a91f9ffa462900b0ca7181ad7f%20--%20Anna%E2%80%99s%20Archive.pdf
2. It just hangs there.

**Expected behavior**
It should redirect to the localhost URL.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 115.8.0esr (64-bit)

**Comment by lidel** [comment] 2024-04-12 14:20
@Geremia I was not able to reproduce with latest Companion ([v3.1.0](https://github.com/ipfs/ipfs-companion/releases/tag/v3.1.0)).


The link you provided is being redirected to localhost gateway, companion does its job.

I suspect your problem is that nobody seems to provide the CID you are trying to request:

- https://delegated-ipfs.dev/routing/v1/providers/bafykbzacec75ad3qwvx4wy7omlw3oc6qbcy3dwjgu776zvs7iojhbx4n2wyze → `Providers: null`
- `ipfs routing findprovs bafykbzacec75ad3qwvx4wy7omlw3oc6qbcy3dwjgu776zvs7iojhbx4n2wyze` → no results

Closing as there is no bug in companion to be fixed.

If you need more help, reach out to community at https://discuss.ipfs.tech/c/help/13

**Closed by lidel** 2024-04-12 14:20 UTC
Labels: need/triage
