### ISSUE TITLE
web+fs:/ links are wrongly redirected to public gateways

### ISSUE THREAD

**Issue by RndFooBar** [ipfs/ipfs-companion#150] opened 2016-09-25 16:53 UTC
The addon redirects `web+fs:/` links, when requested with AJAX, to public gateways even though the custom gateway is available.
### How to reproduce:
1. Open [test.html](https://gist.github.com/RndFooBar/692d6f8840df164c8ace7c071263508b) with firefox
2. The Web Console indicates (through an error of Cross-Origin Request) that the file `https://ipfs.io/ipfs/QmU[...]3Nn` was requested
### Expected Behaviour:

The custom gateway should have been used. 
The requested file should have been:  `http://localhost:8080/ipfs/QmU[...]3Nn` (with default settings)

**Comment by lidel** [comment] 2016-09-26 16:34
Thank you for reporting this. 

This bug is probably caused by limitation of old SDK (security policy blocks request before we replace it with local one).

Let's leave this bug open until it is addressed during WebExtension rewrite (#20).

**Comment by lidel** [comment] 2017-10-15 10:42
This is no longer reproducible under WebExtension version: 
we do not have real protocol handler anymore, only a set of hacks that simulate it (see #164).

I am closing this one, if at some point in future a similar use case could be formulated against WebExtension version, it should be a new issue.

**Closed by lidel** 2017-10-15 10:42 UTC
Labels: blocked by missing API, bug
