### ISSUE TITLE
I do not see all the menu items

### ISSUE THREAD

**Issue by atommixz** [ipfs/ipfs-companion#125] opened 2016-06-24 07:27 UTC
![2016-06-24-102053_1920x1080_scrot](https://cloud.githubusercontent.com/assets/359276/16331013/430a0f88-39fe-11e6-9dd9-d51687a4e4da.png)

I have zoom page 150% by default and it's breaks this addon.

**Comment by lidel** [comment] 2016-07-09 13:11
Thank you for reporting this.

I removed `font-size: small` from status lines -- should improve readability.
The fix will be in next release (v1.5.9)

As for missing menu items, some items are present only in specific contexts.
Which  items were missing? What was the URL in address bar?

**Comment by lidel** [comment] 2016-08-03 18:38
Assuming the issue is gone. Feel free to reopen it still  present in v1.5.9.

**Comment by atommixz** [comment] 2017-06-27 22:51
![2017-06-28-014746_1920x1034_scrot](https://user-images.githubusercontent.com/359276/27613435-2bd1b7d0-5ba4-11e7-9ff0-f65d09065b45.png)
still ugly with default zoom 160%

**Comment by atommixz** [comment] 2017-06-27 23:11
![2017-06-28-020716_1920x1034_scrot](https://user-images.githubusercontent.com/359276/27613903-e656422c-5ba6-11e7-9fb1-139fde8927d6.png)
2.0.0alpha6 unusable with Firefox 54

**Comment by atommixz** [comment] 2017-06-27 23:12
I feel it must be displayed as default, 100% zoom

**Comment by lidel** [comment] 2017-07-09 18:13
@atommixz are you using any additional addons that globally force zoom on all pages (both websites and browser chrome)? Or perhaps a specific GTK  settings/theme?

I tried to zoom with built-in <kbd>+</kbd>/<kbd>-</kbd> menu buttons but it only zooms current tab, browser action popup is atill at 100%. 

Any feedback on how can I replicate this issue would be appreciated.

**Comment by atommixz** [comment] 2017-07-09 18:48
I have problem if I use 'Zoom Page' addon - https://addons.mozilla.org/firefox/addon/zoom-page/
If I disable it, I steel have problem with very popular theme for gtk 'United Gnome' - https://www.gnome-look.org/p/1174889
If I disable it, all fine.
I do not have problem with another FF addons, only this.

**Comment by lidel** [comment] 2017-07-22 12:54
I was unable to replicate with 'Zoom Page' (150%) and 'United Gnome' and [2.0.0alpha7](https://addons.mozilla.org/en-US/firefox/addon/ipfs-gateway-redirect/versions/beta?page=1#version-2.0.0alpha7) of this addon:

> ![2017-07-22-145023_1533x671_scrot](https://user-images.githubusercontent.com/157609/28491201-1eff30a8-6eed-11e7-8ec8-8867c22fca17.png)

I suspect there is something else in play.
Perhaps you have some kind of Userstyle / Stylish customization enabled?

**Closed** 2017-10-08 18:19 UTC
Labels: bug, help wanted, UX
