### ISSUE TITLE
Firefox 55 warns extension is “Legacy”

### ISSUE THREAD

**Issue by da2x** [ipfs/ipfs-companion#270] opened 2017-08-13 20:03 UTC
Version 1.6.0 as published in the Firefox Extension Catalog will stop working in Firefox 57 (due 2017-11-14). The extension is identified by Firefox as using the legacy add-on API and not the new WebExtensions API.

**Comment by lidel** [comment] 2017-08-13 20:18
Thank you for reporting this warning.
It is noted and we are doubling down on migration.

(Closing as a duplicate of #20, where we track Migration to WebExtensions API)

**Closed by lidel** 2017-08-13 20:18 UTC
